FROM golang:1.26.1-alpine AS builder
WORKDIR /app

RUN apk add --no-cache gcc musl-dev

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o bookshelf cmd/bookshelf/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/bookshelf .
EXPOSE 8080
CMD ["./bookshelf"]