// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/validator.proto

package validator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthorValidator_Validate_FullMethodName = "/validator.AuthorValidator/Validate"
)

// AuthorValidatorClient is the client API for AuthorValidator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthorValidatorClient interface {
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type authorValidatorClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorValidatorClient(cc grpc.ClientConnInterface) AuthorValidatorClient {
	return &authorValidatorClient{cc}
}

func (c *authorValidatorClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, AuthorValidator_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorValidatorServer is the server API for AuthorValidator service.
// All implementations must embed UnimplementedAuthorValidatorServer
// for forward compatibility.
type AuthorValidatorServer interface {
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	mustEmbedUnimplementedAuthorValidatorServer()
}

// UnimplementedAuthorValidatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthorValidatorServer struct{}

func (UnimplementedAuthorValidatorServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedAuthorValidatorServer) mustEmbedUnimplementedAuthorValidatorServer() {}
func (UnimplementedAuthorValidatorServer) testEmbeddedByValue()                         {}

// UnsafeAuthorValidatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorValidatorServer will
// result in compilation errors.
type UnsafeAuthorValidatorServer interface {
	mustEmbedUnimplementedAuthorValidatorServer()
}

func RegisterAuthorValidatorServer(s grpc.ServiceRegistrar, srv AuthorValidatorServer) {
	// If the following call panics, it indicates UnimplementedAuthorValidatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthorValidator_ServiceDesc, srv)
}

func _AuthorValidator_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorValidatorServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorValidator_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorValidatorServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthorValidator_ServiceDesc is the grpc.ServiceDesc for AuthorValidator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthorValidator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "validator.AuthorValidator",
	HandlerType: (*AuthorValidatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _AuthorValidator_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/validator.proto",
}
