// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/validator.proto

package validator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        string                 `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_proto_validator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_validator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_proto_validator_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_proto_validator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_validator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_proto_validator_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_validator_proto protoreflect.FileDescriptor

const file_proto_validator_proto_rawDesc = "" +
	"\n" +
	"\x15proto/validator.proto\x12\tvalidator\")\n" +
	"\x0fValidateRequest\x12\x16\n" +
	"\x06author\x18\x01 \x01(\tR\x06author\"@\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2V\n" +
	"\x0fAuthorValidator\x12C\n" +
	"\bValidate\x12\x1a.validator.ValidateRequest\x1a\x1b.validator.ValidateResponseB3Z1github.com/LuhTonkaYeat/bookshelf/proto/validatorb\x06proto3"

var (
	file_proto_validator_proto_rawDescOnce sync.Once
	file_proto_validator_proto_rawDescData []byte
)

func file_proto_validator_proto_rawDescGZIP() []byte {
	file_proto_validator_proto_rawDescOnce.Do(func() {
		file_proto_validator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_validator_proto_rawDesc), len(file_proto_validator_proto_rawDesc)))
	})
	return file_proto_validator_proto_rawDescData
}

var file_proto_validator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_validator_proto_goTypes = []any{
	(*ValidateRequest)(nil),  // 0: validator.ValidateRequest
	(*ValidateResponse)(nil), // 1: validator.ValidateResponse
}
var file_proto_validator_proto_depIdxs = []int32{
	0, // 0: validator.AuthorValidator.Validate:input_type -> validator.ValidateRequest
	1, // 1: validator.AuthorValidator.Validate:output_type -> validator.ValidateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_validator_proto_init() }
func file_proto_validator_proto_init() {
	if File_proto_validator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_validator_proto_rawDesc), len(file_proto_validator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_validator_proto_goTypes,
		DependencyIndexes: file_proto_validator_proto_depIdxs,
		MessageInfos:      file_proto_validator_proto_msgTypes,
	}.Build()
	File_proto_validator_proto = out.File
	file_proto_validator_proto_goTypes = nil
	file_proto_validator_proto_depIdxs = nil
}
